/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KurulumRouteImport } from './routes/kurulum'
import { Route as AuthenticatedPanelK72mRouteImport } from './routes/_authenticated/panel-k72m'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KurulumRoute = KurulumRouteImport.update({
  id: '/kurulum',
  path: '/kurulum',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelK72mRoute = AuthenticatedPanelK72mRouteImport.update({
  id: '/panel-k72m',
  path: '/panel-k72m',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kurulum': typeof KurulumRoute
  '/panel-k72m': typeof AuthenticatedPanelK72mRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kurulum': typeof KurulumRoute
  '/panel-k72m': typeof AuthenticatedPanelK72mRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kurulum': typeof KurulumRoute
  '/_authenticated/panel-k72m': typeof AuthenticatedPanelK72mRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/kurulum' | '/panel-k72m'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/kurulum' | '/panel-k72m'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kurulum'
    | '/_authenticated/panel-k72m'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KurulumRoute: typeof KurulumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurulum': {
      id: '/kurulum'
      path: '/kurulum'
      fullPath: '/kurulum'
      preLoaderRoute: typeof KurulumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel-k72m': {
      id: '/_authenticated/panel-k72m'
      path: '/panel-k72m'
      fullPath: '/panel-k72m'
      preLoaderRoute: typeof AuthenticatedPanelK72mRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelK72mRoute: typeof AuthenticatedPanelK72mRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelK72mRoute: AuthenticatedPanelK72mRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KurulumRoute: KurulumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
